apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc-dynamic
  persistentVolumeReclaimPolicy: Retain
  resources:
    requests:
      storage: 4Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: ebs-dynamic
  labels:
    purpose: ebs-dynamic-test
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim-dynamic

--- 

apiVersion: v1
kind: Service
metadata:
  name: ebs-dynamic-test
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-dynamic-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007

