apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    name: mongodb
    component: roboshop
    teir: db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongodb
      component: roboshop
      teir: db
  template:
    metadata:
      labels:
        name: mongodb
        component: roboshop
        teir: db
    spec:
      containers:
      - name: mongodb
        image: amar1324/mongodb:v1
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 5
          periodSeconds: 5


# Service

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    name: mongodb
    component: roboshop
    teir: db
  ports:
    - protocol: "TCP"
      port: 27017
      targetPort: 27017


